services:
  pgtestdb:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "password"
    restart: unless-stopped
    volumes:
      # Uses a tmpfs volume to make tests extremely fast. The data in test
      # databases is not persisted across restarts, nor does it need to be.
      - type: tmpfs
        target: /var/lib/postgresql/data/
    command:
      - "postgres"
      - "-c" # turn off fsync for speed
      - "fsync=off"
      - "-c" # log everything for debugging
      - "log_statement=all"
    ports:
      # Entirely up to you what port you want to use while testing.
      - "2000:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 30
  migrate:
    build:
      context: .
      dockerfile: migration.Dockerfile
    depends_on:
      pgtestdb:
        condition: service_healthy
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      pgtestdb:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile